capturing
captureException: anException
	^ self captureException: anException in: [ :event |  ]